/*jslint esnext:true */
var citations = [
	"Compter constamment sur les autres quand on est dans la merde, c’est un peu les prendre pour du PQ.",
	"On reconnaît l'âne à ses oreilles, l'ours à ses griffes l'imbécile à ses discours.",
	"Je vous raconterais bien une connerie mais vraiment il y en a plein les journaux.",
	"Il paraît que les efforts sont payants ! J'avais déjà du mal à en faire !",
	"Si j'étais né avant mon père, j'aurais pu être le sien.",
	"L'an dernier j’étais au bord du gouffre, cette année j'ai fait un grand pas en avant.",
	"Si tu mets ceux qui brassent de l'air d'un coté et ceux qui te le pompent de l'autre... Tu as la climatisation gratuite !",
	"Comme le dit souvent ma copine cocaïnomane : tire un trait, tu y verras plus clair.",
	"Qui a une tête de beurre ne doit pas s'approcher du four.",
	"Hier soir, je dis à ma femme : « Ruth, crois-tu que la passion et le sexe, ce soit fini entre nous ? », elle me répond : « On discutera après la pub ».",
	"Le premier gouvernement que j'ai protesté ? ma mère !",
	"Selon mon cour de biologie, l'érection est occasionnée par un afflux sanguin venant du cœur vers le pénis. Les filles, puisqu'on vous dit que ça vient du cœur il faut nous croire !",
	"Les profs c'est comme l'alcool, sa saoul.",
	"Pas étonnant lorsqu'on indique la direction de la lumière et de la connaissance à une dinde, qu'elle prenne la direction opposée.",
	"Une personne ayant un père casse-pied n’a pas forcément une mère Caspienne.",
	"Fondue enchaînée  : Soirée sado-maso savoyarde.",
	"Progrès : Phénomène qui permet d’acheter un VTT en PVC auprès d’une société de VPC, en appelant les PTT en PCV.",
	"Drame en Sologne : un chasseur confond son fils avec un sanglier... et donne une gifle au sanglier!",
	"On vient enfin de décrypter la pierre de Rosette : le texte est en fait la recette du couscous",
	"L'an dernier j'étais encore un peu prétentieux, cette année je suis parfait.",
	"Si tu dors et que tu rêves que tu dors, il faut que tu te réveilles deux fois pour te lever.",
	"Les avis c'est comme les trou du cul......tout le monde en a un !!!",
	"On a tous besoin de croire en quelque chose, moi je crois que je vais me servir un autre ricard !",
	"Comment vérifier que la petite lumière dans le frigo est vraiment éteinte quand on ferme la porte ?",
	"Tout le monde pense que je suis hypocondriaque. Ça me rend malade.",
	"Une journée sans humour ou sans rire ressemble à un bol de soupe sans jus.",
	"Ne rien faire, mais le faire bien.",
	"C'est au moment où tu vois un moustique se poser sur tes testicules que tu te rends compte qu'il y a moyen de régler certains problèmes autrement que par la violence.",
	"Certains ont peur du vide, moi vu le prix de l'essence j'ai plutôt peur du plein !",
	"Si j'avais mis de côté tout l'argent que j'ai dépensé à boire, qu'est-ce que je pourrais m'offrir comme apéritifs !",
	"Tarzan a mal tourné car il a été élevé avec des singes qui n'étaient pas de son âge.",
	"Steak dare-dare : Steak servi dans les fast-foods.",
	"Les Mains Sales : Pièce de Sartre qui a été adaptée en Suisse sous le titre L’'Emmenthal, ce qui a pour conséquence que les acteurs ont souvent des trous de mémoire.",
	"Récalcitron : Citron qui refuse de se laisser cueillir.",
	"Personne dans ce monde devrait se considérer comme un gros nul, car nous sommes tous arrivés les premiers de la course à l’ovule.",
	"Il n'est pas nécéssaire, d'être forcément né à La Havane, pour être un concubin....",
	"Les faux-culs, c'est comme les répondeurs : ça parle toujours quand tu es pas là !",
	"J'aimerais être un pc, pour pouvoir redémarrer ma vie en mode sans échec.",
	"L'amour rend fou. Il n'y a que la guerre qui Rambo.",
	"Eh mec ! Dis ça a un unijambiste ! Comme ça, ça lui fera une belle jambe pour courir !",
	"Qui fait l'âne ne doit pas s'étonner si les autres lui montent dessus.",
	"Ne croyez pas qu'en laissant vos cheveux chez le coiffeur, vous l'avez payé.",
	"Moi j'ai dit bizarre, bizarre, comme c'est étrange ! Pourquoi aurais-je dit bizarre, bizarre ?",
	"Trop bon, trop con.......NON........trop con, TROP con !",
	"Je sens que ma dernière heure est arrivée, je voudrais la passer avec vous.",
	"Il faut manger comme un homme en bonne santé et boire comme un malade.",
	"Je me suis réveillé ce matin, j' ai levé les bras, et crac ! J' ai plié les genoux, et crac ! J 'ai tourné le cou, et crac ! Alors, j'en suis venu à la conclusion suivante : plus on est vieux plus on est craquant !",
	"Secret : Information que l’on ne communique qu’à une seule personne à la fois.",
	"Si vous avez compris tout ce que je viens de vous dire, c'est que j'ai dû faire une erreur quelque part.",
	"Quand on ne sait pas où l'on va, tous les chemins mènent nulle part.",
	"Si vous ne savez pas ou vous allez, vous vous retrouverez sûrement ailleurs.",
	"Les hémorroïdes gagnent du terrain, les chercheurs se grattent la tête.",
	"Les lapsus c'est comme les cunnilingus, un écart de langue et tu te retrouves dans la merde.",
	"A la naissance le nain est normal c'est en grandissant qu'il rapetisse.",
	"Ce n'est pas parce que l'homme a soif d'amour qu'il doit se jeter sur la première gourde.",
	"C'est quand on est dans la merde jusqu'au cou qu'il faut marcher la tête haute.",
	"Au cours d'un repas : Tu vois chérie, j'avais déjà marché dedans, mais j'en avais jamais mangé.",
	"Je ne connais absolument rien à la musique, mais dans mon domaine ce n'est pas nécessaire.",
	"Elle chante tellement faux que même les sourds refusent de regarder ses lèvres bouger.",
	"J'ai vu un film tellement mauvais que les gens faisaient la queue pour sortir de la salle.",
	"Si vous voulez maigrir, suivez mon conseil : mangez autant que vous voulez, mais recrachez tout.",
	"Alors qu'elle était allongée à côté de moi, une petite voix me disait &quot;Tu n'es pas le premier docteur qui couche avec une de ses patientes&quot;, mais une autre voix me répétait : &quot;Howard, tu es vétérinaire !&quot;.",
	"Si on ne peut pas fumer au paradis, je ne suis pas intéressé.",
	"Le labour est au boeur ce que l'amour est aux meufs",
	"Les conneries c'est comme les impôts , tu finis toujours par les payer",
	"J'connaîtrai jamais le bonheur sur terre. Je suis bien trop con.",
	"Tu as à peu près autant de charme qu’une limace crevée !",
	"Si voter changeait quelque chose, il y a longtemps que ça serait interdit.",
	"Le spermatozoïde est un bandit à l'état pur.",
	"L'erreur est humaine mais pour un vrai désastre ça vous prend un ordinateur.",
	"Ne t'inquiète pas si tu as des difficultés en maths ,je peux t'assurer que les miennes sont bien plus importantes.",
	"Le pire ennemi, c'est soi-même, Mais je ne le tue, car je l'aime.",
	"Goéland qui s'gratte le gland Signe de mauvais temps Goéland qui s'gratte le cul F'ra pas beau non plus",
	"C'est en sciant que Léonard devint scie.",
	"On reconnaît le rouquin aux cheveux du père et le requin aux dents de la mère...",
	"Les amis c'est comme les seins; il y en a des petits, des grands... des vrais et des faux...",
	"Mieux vaut être un clown q'un clone.",
	"Ce sont souvent les habitants des pays les plus reculés qui vivent jusqu’à l’âge le plus avancé",
	"Dans le Sentier, les tailleurs sont souvent de confection juive",
	"Avant je me souviens à la plage, il fallait écarter le maillot pour voir les fesses, aujourd'hui il faut écarter les fesses pour voir le maillot !",
];
export default citations;